spring.application.name=contact-manager
server.port=8282

spring.datasource.url=jdbc:postgresql://localhost:5432/contact-manager?serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.filePath=/home/sahabuddin/durgesh/project_files

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kazi.sahabuddin16@gmail.com
spring.mail.password=qcou pemv yegt gjog
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=kazi.sahabuddin16@gmail.com
